encoding: UTF-8
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Grey

description: > # this means to ignore newlines until "baseurl:"
  It's that GReyes!
baseurl: "" # the subpath of your site, e.g. /blog

#google_analytics: 
github_username:  greyes1


# Build settings
markdown: kramdown





